{% set name = "creme" %}
{% set version = "0.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/creme-ml/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c9b199fc97bd2631066645728634335d1dc4f7066eddb1c6f2c57b2769b030fc

build:
  skip: true  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.29.6
  run:
    - numpy >=1.16.4
    - python
    - scikit-learn >=0.21.2
    - scipy >=1.3.0
    - cython >=0.29.6
    - mmh3

test:
  imports:
    - creme
    - creme.anomaly
    - creme.cluster
    - creme.compat
    - creme.compose
    - creme.decomposition
    - creme.ensemble
    - creme.feature_extraction
    - creme.feature_selection
    - creme.impute
    - creme.linear_model
    - creme.metrics
    - creme.multiclass
    - creme.multioutput
    - creme.naive_bayes
    - creme.neighbors
    - creme.optim
    - creme.optim.losses
    - creme.preprocessing
    - creme.proba
    - creme.reco
    - creme.stats
    - creme.tree
    - creme.utils

about:
  home: "https://github.com/creme-ml/creme"
  license: BSD-3-Clause
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "Incremental machine learning in Python"
  doc_url: "https://creme-ml.github.io"
  dev_url: "https://github.com/creme-ml/creme"

extra:
  recipe-maintainers:
    - agcopenhaver
    - rluria14
    - oblute
