{% set name = "creme" %}
{% set version = "0.4.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/creme-ml/{{ name }}/archive/{{ version }}.tar.gz
  sha256: "57e247ead599e147bdda07a42d5457fd4e412376b6d013084ee870c8be884f06"
  patches:
    # This is to make it build for windows.
    - patch.diff

build:
  skip: true  # [py<36]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.29.6
  run:
    - numpy >=1.16.4
    - python
    - scikit-learn >=0.21.2
    - scipy >=1.3.0
    - cython >=0.29.6

test:
  imports:
    - creme
    - creme.anomaly
    - creme.cluster
    - creme.compat
    - creme.compose
    - creme.decomposition
    - creme.ensemble
    - creme.feature_extraction
    - creme.feature_selection
    - creme.impute
    - creme.linear_model
    - creme.metrics
    - creme.multiclass
    - creme.multioutput
    - creme.naive_bayes
    - creme.neighbors
    - creme.optim
    - creme.optim.losses
    - creme.preprocessing
    - creme.proba
    - creme.reco
    - creme.stats
    - creme.tree
    - creme.utils

about:
  home: "https://github.com/creme-ml/creme"
  license: BSD-3-Clause
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "Incremental machine learning in Python"
  doc_url: "https://creme-ml.github.io"
  dev_url: "https://github.com/creme-ml/creme"

extra:
  recipe-maintainers:
    - agcopenhaver
