{% set name = "creme" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 676c7bdc8d450d4ca96e3dd471c10e5125242108be9f857fd46954d0916c70bb

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.29.6
  run:
    - numpy >=1.16.4
    - python
    - scikit-learn >=0.21.2
    - scipy >=1.3.0
    - cython >=0.29.6
    - mmh3
    - pandas

test:
  imports:
    - creme
    - creme.anomaly
    - creme.cluster
    - creme.compat
    - creme.compose
    - creme.decomposition
    - creme.ensemble
    - creme.feature_extraction
    - creme.feature_selection
    - creme.impute
    - creme.linear_model
    - creme.metrics
    - creme.multiclass
    - creme.multioutput
    - creme.naive_bayes
    - creme.neighbors
    - creme.optim
    - creme.optim.losses
    - creme.preprocessing
    - creme.proba
    - creme.reco
    - creme.stats
    - creme.tree
    - creme.utils

about:
  home: "https://github.com/creme-ml/creme"
  license: BSD-3-Clause
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "Incremental machine learning in Python"
  doc_url: "https://creme-ml.github.io"
  dev_url: "https://github.com/creme-ml/creme"

extra:
  recipe-maintainers:
    - mxr-conda
