travis:
  secure:
    BINSTAR_TOKEN: m1a8UvTXd3n6Ni3JN0NEdNVTgG1uC/C94SBZzhBVTRkLQkjtqXzd21DuUxRkAs7WZpGIB2ju3V9VuwoIVcDhitqRNsBEHX3GoU8pCz/INlE6lLXF2K2ciGxIpRhnzD2PlNIB82CkEuZWujYoVEeOnx2WPdHaTGFzAq3gbehXrTtdhlAxxdAM7Qg0Q6nhNkD+ZDLIdbqE/JAdY2Rzzksjaiy2ptvJJxTZdjEZit+1FbfeTbYAdafuBjwF3EtbXAPwi0id/fN0z+jmGWUi5VvrAmDJ8BJGt2YQT16bKQSV1RzgNESaynxxSE0nVLNxDee0num9oGemTjCwYIN3PB2zJFbmKXUMSEjDmw8qkd7FHp4LS3shwNemKpRNrsUUoXWNY9vvDPY2YIqkKwgadcspiMGaVvD/zb+htxmfWqMpO5vHCxucghLTCMPCjpqYC/nGh4zMTYFYAJr7eIu+eXS8R8j5M7yn6aqpF852d10dv/VXwVaONunY1E2axpsnKrNuMZcO5EZvVdnywt0QJRn/d5NrpEAFGQPV04FUD2dPnUCCZoq4H9piVI+aMazfxVcpDspsO1vPhI7xAxLuSFwnSccAhz7HgJ8zhlixvJuE5GWSZzfNI9lYKFFo+dibcvovHWrn+xxfvUTNqVoVtL9vDNIKNZ9f41O9g8yneR5HkuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
